# Generated by Django 2.1.5 on 2019-01-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('logo', models.URLField(blank=True, max_length=254, null=True, verbose_name='Logo')),
                ('uri', models.URLField(max_length=255, verbose_name='URI')),
                ('group_title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Group Title')),
                ('status', models.IntegerField(default=200, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canais',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(blank=True, max_length=254, null=True, verbose_name='Group Title')),
            ],
        ),
        migrations.AddField(
            model_name='canal',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='canal_grupos', to='canais.Grupo', verbose_name='grupos'),
        ),
    ]
